# Minimal values for ingress-nginx with kind
controller:
  replicaCount: 1
  hostNetwork: true
  dnsPolicy: ClusterFirstWithHostNet
  service:
    type: ClusterIP
  admissionWebhooks:
    enabled: true