apiVersion: batch/v1
kind: Job
metadata:
  name: gitea-init-admin
  namespace: platform
spec:
  template:
    spec:
      restartPolicy: OnFailure
      containers:
        - name: init
          image: gitea/gitea:1.22.3
          command: ["bash","-lc"]
          args:
            - >-
              gitea admin user create --admin --username admin --password admin123 --email admin@gitea.local || true